version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (github.com/bsm/bfs.Bucket).Close
        - (github.com/bsm/bfs.Iterator).Close
        - (github.com/bsm/bfs.Reader).Close
        - (github.com/bsm/bfs.Writer).Discard
        - (*os.File).Close
        - os.Remove
        - os.RemoveAll
