name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    uses: bsm/misc/.github/workflows/test-go.yml@main
    with:
      working-directory: .
  ftp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: bsm/misc/.github/actions/lint-go@main
        with:
          working-directory: bfsftp
  ftp-test:
    runs-on: ubuntu-latest
    services:
      ftp_server:
        image: delfer/alpine-ftp-server
        ports:
          - 7021:21
          - 21000-21010:21000-21010
        env:
          USERS: "ftpuser|ftppass"
    steps:
      - uses: bsm/misc/.github/actions/test-go@main
        with:
          working-directory: bfsftp
  scp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: bsm/misc/.github/actions/lint-go@main
        with:
          working-directory: bfsscp
  scp-test:
    runs-on: ubuntu-latest
    services:
      ssh_server:
        image: sickp/alpine-sshd:7.5-r2
        ports:
          - 7022:22
    steps:
      - uses: bsm/misc/.github/actions/test-go@main
        with:
          working-directory: bfsscp
  # gs:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfsgs
  # s3:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfss3
  # scp:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfsscp
