name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    services:
      ftp_server:
        image: delfer/alpine-ftp-server
        ports:
          - 7021:21
          - 21000-21010:21000-21010
        env:
          USERS: "ftpuser|ftppass"
      ssh_server:
        image: sickp/alpine-sshd:7.5-r2
        ports:
          - 7022:22
    steps:
      - name: Fetch staticcheck
        uses: engineerd/configurator@v0.0.6
        with:
          name: staticcheck
          fromGitHubReleases: true
          repo: dominikh/go-tools
          version: latest
          urlTemplate: "https://github.com/dominikh/go-tools/releases/download/2020.2.3/staticcheck_linux_amd64.tar.gz"
          pathInArchive: staticcheck/staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run tests
        run: make test
      - name: Run staticcheck
        run: make staticcheck
