name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    uses: bsm/misc/.github/workflows/test-go.yaml@main
    with:
      working-directory: .
  # ftp:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfsftp
  # gs:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfsgs
  # s3:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfss3
  # scp:
  #   uses: bsm/misc/.github/workflows/test-go.yaml@main
  #   with:
  #     working-directory: bfsscp
